### ISSUE TITLE
Update pls.

### ISSUE THREAD

**Issue by ATrigger** [mradermaxlol/pontostroy-wine#2]
https://github.com/iXit/Mesa-3D/issues/102#issuecomment-215317695

**Comment by mradermaxlol** [comment]
@ATrigger it's noy repo's issue - tell that to @pontostroy - he'll be able to do something.

I'll actually do some research later and maybe I'll fix it here.

**Comment by ATrigger** [comment]
yet it(repo) contains critical bug that is fixed in upstream wine

**Comment by mradermaxlol** [comment]
@ATrigger yet it does, but it's not this repo's issue, as the latter's just a mirror.

**Comment by mradermaxlol** [comment]
Closing, take a look [there](https://github.com/mradermaxlol/pontostroy-wine/commit/6c9c20a9e9fc3ab85a0e37bf4b9a64f66321f943).
